package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "ethernet_receiver",
    srcs = ["ethernet_receiver.cc"],
    deps = [
        "//cyber",
        "//modules/ethernet/proto:ethernet_test_cc_proto",
    ],
)

cc_binary(
    name = "ethernet_sender",
    srcs = ["ethernet_sender.cc"],
    deps = [
        "//cyber",
        "//modules/ethernet/proto:ethernet_test_cc_proto",
    ],
)

